import { useState, useEffect } from "react";
import { useBranchStore } from "../store";
import { saveSettings, getOrCreateSettings } from "../db";
import { C } from "./theme";

const TOOLTIP: Record<string, string> = {
  local:  "Node labels are generated locally using the first ~60 characters of your prompt. Fast, private, no API needed.",
  gemini: "Node labels and branch predictions are generated by Gemini 2.0 Flash (8-word summaries). Requires an API key. Uses ~2 API calls per conversation turn.",
};

function Tooltip({ text }: { text: string }) {
  const [show, setShow] = useState(false);
  return (
    <span
      style={{ position: "relative", display: "inline-flex", alignItems: "center" }}
      onMouseEnter={() => setShow(true)}
      onMouseLeave={() => setShow(false)}
    >
      <span style={{
        display: "inline-flex", alignItems: "center", justifyContent: "center",
        width: 14, height: 14, borderRadius: "50%",
        background: C.surface1, color: C.overlay1,
        fontSize: 9, fontWeight: 700, cursor: "default", flexShrink: 0,
      }}>?</span>
      {show && (
        <span style={{
          position: "absolute", bottom: "calc(100% + 6px)", left: 0,
          width: 200, background: C.crust, border: `1px solid ${C.surface1}`,
          borderRadius: 8, padding: "7px 10px",
          fontSize: 10, color: C.subtext1, lineHeight: 1.5,
          boxShadow: "0 4px 12px rgba(0,0,0,0.12)",
          pointerEvents: "none", zIndex: 100,
          whiteSpace: "normal",
        }}>
          {text}
        </span>
      )}
    </span>
  );
}

function Toggle({ on, onToggle }: { on: boolean; onToggle: () => void }) {
  return (
    <div
      style={{ width: 32, height: 18, borderRadius: 9, position: "relative", flexShrink: 0,
        background: on ? C.mauve : C.surface1, transition: "background 0.2s", cursor: "pointer" }}
      onMouseDown={(e) => { e.stopPropagation(); onToggle(); }}
    >
      <div style={{
        position: "absolute", top: 3, width: 12, height: 12,
        borderRadius: "50%", background: "#fff",
        transition: "left 0.2s", left: on ? 17 : 3,
      }} />
    </div>
  );
}

export function SettingsPanel() {
  const geminiApiKey       = useBranchStore((s) => s.geminiApiKey);
  const driftThreshold     = useBranchStore((s) => s.driftThreshold);
  const autoDetectBranches = useBranchStore((s) => s.autoDetectBranches);
  const storeSummaryMode   = useBranchStore((s) => s.summaryMode);
  const setSettings        = useBranchStore((s) => s.setSettings);

  const [apiKey, setApiKey]           = useState(geminiApiKey);
  const [threshold, setThreshold]     = useState(driftThreshold);
  const [autoDetect, setAutoDetect]   = useState(autoDetectBranches);
  const [summaryMode, setSummaryMode] = useState<"gemini" | "local">(storeSummaryMode ?? "local");
  const [saved, setSaved]             = useState(false);
  const [error, setError]             = useState("");

  useEffect(() => {
    getOrCreateSettings()
      .then((s) => {
        setApiKey(s.geminiApiKey);
        setThreshold(s.driftThreshold);
        setAutoDetect(s.autoDetectBranches);
        setSummaryMode(s.summaryMode ?? "local");
      })
      .catch((e) => setError(String(e)));
  }, []);

  const handleSave = async () => {
    try {
      const updates = { geminiApiKey: apiKey, driftThreshold: threshold, autoDetectBranches: autoDetect, summaryMode };
      await saveSettings(updates);
      setSettings(updates);
      setSaved(true);
      setTimeout(() => setSaved(false), 2000);
    } catch (e) {
      setError(String(e));
    }
  };

  const inputStyle: React.CSSProperties = {
    width: "100%", background: C.base,
    border: `1px solid ${C.surface1}`,
    borderRadius: 6, padding: "6px 10px",
    fontSize: 11, color: C.text, outline: "none",
    boxSizing: "border-box",
  };

  const sectionLabel = (text: string) => (
    <div style={{ fontSize: 10, fontWeight: 700, color: C.overlay1, textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 10 }}>
      {text}
    </div>
  );

  return (
    <div style={{ padding: 12, display: "flex", flexDirection: "column", gap: 20, color: C.text }}>

      {error && (
        <div style={{ padding: 8, background: "#ffecee", border: `1px solid ${C.red}`, borderRadius: 6, fontSize: 11, color: C.red }}>
          {error}
        </div>
      )}

      {/* Node Labels */}
      <div>
        {sectionLabel("Node Labels")}
        <div style={{ display: "flex", gap: 6, marginBottom: 10 }}>
          {(["local", "gemini"] as const).map((mode) => {
            const active = summaryMode === mode;
            return (
              <button
                key={mode}
                onMouseDown={(e) => { e.stopPropagation(); e.preventDefault(); setSummaryMode(mode); }}
                style={{
                  flex: 1, padding: "7px 0", borderRadius: 8, cursor: "pointer",
                  fontSize: 11, fontWeight: active ? 700 : 400,
                  border: `1.5px solid ${active ? C.mauve : C.surface1}`,
                  background: active ? C.mantle : C.base,
                  color: active ? C.mauve : C.overlay1,
                  transition: "all 0.15s",
                }}
              >
                {mode === "local" ? "Local" : "AI (Gemini)"}
              </button>
            );
          })}
        </div>
        <div style={{ display: "flex", alignItems: "flex-start", gap: 6, background: C.crust, borderRadius: 8, padding: "7px 10px" }}>
          <Tooltip text={TOOLTIP[summaryMode]} />
          <span style={{ fontSize: 10, color: C.subtext1, lineHeight: 1.5 }}>
            {summaryMode === "local"
              ? "Labels use the first ~60 chars of your prompt — instant, no API needed."
              : "Labels are 8-word AI summaries generated by Gemini — more descriptive, uses API quota."}
          </span>
        </div>
      </div>

      {/* Gemini API Key */}
      <div>
        {sectionLabel("Gemini API Key")}
        <label style={{ display: "block", fontSize: 11, color: C.subtext0, marginBottom: 4 }}>
          Required for AI labels and branch predictions
        </label>
        <input
          type="password" value={apiKey} placeholder="AIza..."
          onChange={(e) => setApiKey(e.target.value)}
          style={{ ...inputStyle, opacity: summaryMode === "local" ? 0.45 : 1 }}
        />
        <div style={{ fontSize: 10, color: C.overlay1, marginTop: 4 }}>
          Never leaves your browser.
        </div>
      </div>

      {/* Drift Detection */}
      <div>
        {sectionLabel("Drift Detection")}

        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 14 }}>
          <Toggle on={autoDetect} onToggle={() => setAutoDetect((v) => !v)} />
          <span style={{ fontSize: 11, color: C.text }}>Auto-detect side quests</span>
          <Tooltip text="When enabled, BranchBarber automatically flags turns that drift significantly from the previous topic as a Side Quest." />
        </div>

        <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 4 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 5 }}>
            <span style={{ fontSize: 11, color: C.subtext0 }}>Drift Threshold</span>
            <Tooltip text="How much topic change triggers a branch. Lower = more sensitive (flags small shifts). Higher = more relaxed (only flags big jumps)." />
          </div>
          <span style={{ fontSize: 11, fontWeight: 700, color: C.mauve }}>{Math.round(threshold * 100)}%</span>
        </div>
        <input
          type="range" min="0.3" max="0.9" step="0.05" value={threshold}
          onChange={(e) => setThreshold(parseFloat(e.target.value))}
          style={{ width: "100%", accentColor: C.mauve }}
        />
        <div style={{ display: "flex", justifyContent: "space-between", fontSize: 10, color: C.overlay1, marginTop: 2 }}>
          <span>Sensitive</span><span>Relaxed</span>
        </div>
      </div>

      <button
        onMouseDown={(e) => { e.stopPropagation(); e.preventDefault(); handleSave(); }}
        style={{
          padding: "8px 0", borderRadius: 8, border: "none", cursor: "pointer",
          fontWeight: 700, fontSize: 12,
          background: saved ? C.green : C.mauve,
          color: "#fff", transition: "background 0.2s",
        }}
      >
        {saved ? "✓ Saved" : "Save Settings"}
      </button>

      <div style={{ textAlign: "center", fontSize: 10, color: C.overlay1 }}>
        BranchBarber v1.0.0 · Local-first · No telemetry
      </div>
    </div>
  );
}
